### ISSUE TITLE
Starting a detached process

### ISSUE THREAD

**Issue by shreyashsaitwal** [google/process_runner#22]
Hi,

Is it possible to start a detached process using `ProcessRunner.runProcess()`? I know this can be done using dart:io, but I want to do it using this package for the sake of consistency across my project.

cc @gspencergoog

**Comment by gspencergoog** [comment]
When you say "detatched process", are you talking about something like bash's "disown" command, or do you mean the difference between `Process.run` and `Process.start`?

`ProcessRunner.runProcess` code uses `Process.start` inside.

**Comment by shreyashsaitwal** [comment]
I'm not quite familiar with how Bash's disown command works, but what I mean by "detached" is that the spawned child process should continue running even after the parent exits (or is forcefully killed).

**Comment by gspencergoog** [comment]
Ahh, so you mean the `ProcessStartMode.detached` then? ([ProcessStartMode](https://api.dart.dev/stable/2.12.4/dart-io/ProcessStartMode-class.html))

There isn't currently a way to do that in process_runner. I could easily add that as a parameter, but I'm not sure exactly what that would mean, since detached really just means "start this process and disconnect from it", so `ProcessRunner` really doesn't add much value in that scenario: it wouldn't be able to provide output or exit code information, only the PID.

**Comment by shreyashsaitwal** [comment]
> Ahh, so you mean the `ProcessStartMode.detached` then?

Yes, that's correct.

> so ProcessRunner really doesn't add much value in that scenario: it wouldn't be able to provide output or exit code information, only the PID

I guess, it'd be quite helpful in some niche senarios, such as updating your CLI applications. On Mac and Linux you can easily delete the current running executable and replace it with a new one, but on Windows, it's not possible to do that. Having the ability to start a detached process would make it fairly simple to update the executable. 

> I could easily add that as a parameter

It'd be very nice if you'd do that. Looking forward to your response. 😃

**Comment by gspencergoog** [comment]
@ShreyashSaitwal Thanks for the request, 4.0.1 should do what you want.

**Comment by shreyashsaitwal** [comment]
Thanks a lot, @gspencergoog! 😃
